### ISSUE TITLE
Ignore me

### ISSUE THREAD

**Issue by Efreak** [cantorsdust/AllProfessions#1]
```
[14:21:26 INFO  SMAPI] SMAPI 1.9-beta.8 with Stardew Valley 1.2.9 on Microsoft Windows NT 6.2.9200.0
.........
.........
[14:21:26 ERROR SMAPI] Couldn't load mod for manifest 'C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\AllProfessions\manifest.json': an error occurred while preprocessing 'AllProfessions.dll'.
System.ArgumentNullException: Value cannot be null.
Parameter name: method
   at Mono.Cecil.ModuleDefinition.Import(MethodBase method)
   at StardewModdingAPI.AssemblyRewriters.Rewriters.SDV1_2.Game1_Player_FieldRewriter.Rewrite(ModuleDefinition module, ILProcessor cil, Instruction instruction, FieldReference fieldRef, PlatformAssemblyMap assemblyMap)
   at StardewModdingAPI.AssemblyRewriters.Framework.BaseFieldRewriter.Rewrite(ModuleDefinition module, ILProcessor cil, Instruction instruction, PlatformAssemblyMap assemblyMap)
   at StardewModdingAPI.Framework.AssemblyLoader.RewriteAssembly(AssemblyDefinition assembly) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Framework\AssemblyLoader.cs:line 207
   at StardewModdingAPI.Framework.AssemblyLoader.Load(String assemblyPath) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Framework\AssemblyLoader.cs:line 75
```

SDV identifies itself in-game as 1.11, however SMAPI console identifies it as 1.2.9.

**Comment by Efreak** [comment]
Feel free to ignore this, my bad. I play SDV thru family sharing, and it hadn't updated because family sharing broke...
